version: "3.7"
services:
 ogm2pgbm:
    container_name: ogm2pgbm
    image: ghcr.io/saha-robotics/ogm2pgbm:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 50s
        max_attempts: 5      
    volumes:
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
      - type: bind 
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix    
      - type: bind 
        source: ${XAUTHORITY}  
        target: ${XAUTHORITY}        
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    # entrypoint: /ros_entrypoint.sh