name: container-builder

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # self-hosted
    ##############################################################
    ## Configurations
    ##############################################################
    env:
      builder_ns: ghcr.io/saha-robotics/ogm2pgbm
      tag: latest
    ##############################################################
    steps:
      # ###
      # Login to github packages, our container registry
      # ###
      - name:  Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry:  ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v3

  
      # ###
      # build image
      # ###
      -
        name: Build rmf
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          build-args: |
            BUILDER_NS=${{ env.builder_ns }}
            TAG=${{ env.tag }}
          push: true
          tags: ${{ env.builder_ns }}:${{ env.tag }}

 